const DateTimeFormat = {
  DATE_DISPLAY: 'YYYY/MM/DD',
  DATE_DEFAULT_DATEBOX: 'YYYY-MM-DD',
  DATE_MMDDYYYY: 'MM/DD/YYYY',
  DATE_YYYYMMDDHHmm: 'YYYY/MM/DD HH:mm',
  DATE_YYYYMD: 'YYYY/M/D',
  DATE_PARAMS: 'YYYYMMDD',
  DATE_SOLUTION: 'MMM DD, YY',
  DATE: 'DD',
  WEEK_DATE: 'ddd',
  MONTH: 'MMM',
  YEAH: 'YYYY',
  TOOLTIP_DISPLAY: 'ddd, DD-MM-YYYY',
};

export default DateTimeFormat;
