import { MasterProperty, PermissionFull } from '@/shared/MasterProperty';
import { Permissions } from '@/constants/Permissions';

export const MenuData = [
    {
        "id": 1,
        "title": "ホーム",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": MasterProperty.FSHI0015.SSHI0038.Path,
        "permission": MasterProperty.FSHI0015.SSHI0038.Permission,
        "isVisible": true,
    },
    {
        "id": 2,
        "title": "お知らせ",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": "",
        "permission": [Permissions.Agent, Permissions.CustomerManager, Permissions.GroupManager, Permissions.BranchManager, Permissions.CustomerContractor, Permissions.GroupContractor, Permissions.BranchContractor],
        "isVisible": true,
    },

    {
        "id": 3,
        "title": "契約管理",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": MasterProperty.FSHI0010.SSHI0026.Path,
        "permission": MasterProperty.FSHI0010.SSHI0026.Permission,
        "isVisible": true,
    },

    {
        "id": 4,
        "title": "排出物管理",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": MasterProperty.FSHI0011.SSHI0031.Path,
        "permission": MasterProperty.FSHI0011.SSHI0031.Permission,
        "isVisible": true,
    },

    {
        "id": 5,
        "title": "集計レポート",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": MasterProperty.FSHI0014.SSHI0036.Path,
        "permission": MasterProperty.FSHI0014.SSHI0036.Permission,
        "isVisible": true,
    },

    {
        "id": 6,
        "title": "設定",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": "",
        "permission": [Permissions.Agent, Permissions.CustomerManager, Permissions.GroupManager, Permissions.BranchManager, Permissions.CustomerContractor, Permissions.GroupContractor, Permissions.BranchContractor],
        "isVisible": true,
    },

    {
        "id": 7,
        "title": "排出事業者選択",
        "titleInfo": "A会社",
        "parentId": 0,
        "link": MasterProperty.FSHI0009.SSHI0025.Path,
        "permission": MasterProperty.FSHI0009.SSHI0025.Permission,
        "isVisible": true,
    },
    {
        "id": 8,
        "title": "お知らせ",
        "titleInfo": "重要",
        "parentId": 2,
        "link": MasterProperty.FSHI0012.SSHI0035Important.Path,
        "permission": MasterProperty.FSHI0012.SSHI0035Important.Permission,
        "isVisible": true,
    },

    {
        "id": 9,
        "title": "お知らせ",
        "titleInfo": "承認依頼",
        "parentId": 2,
        "link": MasterProperty.FSHI0012.SSHI0035Request.Path,
        "permission": MasterProperty.FSHI0012.SSHI0035Request.Permission,
        "isVisible": true,
    },
    {
        "id": 10,
        "title": "お知らせ",
        "titleInfo": "終了報告",
        "parentId": 2,
        "link": MasterProperty.FSHI0012.SSHI0035Report.Path,
        "permission": MasterProperty.FSHI0012.SSHI0035Report.Permission,
        "isVisible": true,
    },
    {
        "id": 11,
        "title": "お知らせ",
        "titleInfo": "その他",
        "parentId": 2,
        "link": MasterProperty.FSHI0012.SSHI0035Other.Path,
        "permission": MasterProperty.FSHI0012.SSHI0035Other.Permission,
        "isVisible": true,
    },
    {
        "id": 12,
        "title": "お知らせ",
        "titleInfo": "エラー通知",
        "parentId": 2,
        "link": MasterProperty.FSHI0012.SSHI0035Error.Path,
        "permission": MasterProperty.FSHI0012.SSHI0035Error.Permission,
        "isVisible": true,
        "isHr": true
    },
    {
        "id": 13,
        "title": "排出事業者設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0001.SSHI0001.Path,
        "permission": MasterProperty.FSHI0001.SSHI0001.Permission,
        "isVisible": true,
    },
    {
        "id": 14,
        "title": "排出事業場設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0002.SSHI0004.Path,
        "permission": MasterProperty.FSHI0002.SSHI0004.Permission,
        "isVisible": true,
    },
    {
        "id": 15,
        "title": "排出事業場グループ設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0003.SSHI0007.Path,
        "permission": MasterProperty.FSHI0003.SSHI0007.Permission,
        "isVisible": true,
    },
    {
        "id": 16,
        "title": "収集運搬業者設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0004.SSHI0010.Path,
        "permission": MasterProperty.FSHI0004.SSHI0010.Permission,
        "isVisible": true,
        "isHr": true
    },
    {
        "id": 17,
        "title": "処分業者設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0005.SSHI0013.Path,
        "permission": MasterProperty.FSHI0005.SSHI0013.Permission,
        "isVisible": true,
        "isHr": true
    },
    {
        "id": 18,
        "title": "処分事業場設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0006.SSHI0016.Path,
        "permission": MasterProperty.FSHI0006.SSHI0016.Permission,
        "isVisible": true,
    },
    {
        "id": 19,
        "title": "担当者設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0007.SSHI0019.Path,
        "permission": MasterProperty.FSHI0007.SSHI0019.Permission,
        "isVisible": true,
        "isHr": true
    },
    {
        "id": 20,
        "title": "システム設定",
        "titleInfo": "",
        "parentId": 6,
        "link": MasterProperty.FSHI0008.SSHI0022.Path,
        "permission": MasterProperty.FSHI0008.SSHI0022.Permission,
        "isVisible": true,
        "isHr": true
    }
]